### ISSUE TITLE
I don't think beeps are working anymore...

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/stoptalking#19]
Nothing happens when I enable it on Chrome+Mac with sound on, after verifying Youtube does play audio. 🤔

**Comment by danstiner** [comment]
Didn't work on Android for me :(

**Comment by JoshuaKGoldberg** [comment]
@danstiner the issue was I forgot to call `useBeeper`. Lol.

**Comment by danstiner** [comment]
lol

![2010 04-roadrunner](https://user-images.githubusercontent.com/52513/73128797-9a4c9100-3f89-11ea-9ec3-e531f490e0b4.jpg)
